import json
import hashlib
import os
from pathlib import Path
import tempfile
import unittest

import ida_accept
import project_init
import source_index


class ProjectBootstrapTests(unittest.TestCase):
    def test_initializer_uses_user_short_name_for_native_artifacts(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)/'FightingForce-xport'
            config = project_init.initialize(root, 'Fighting Force', 'FF', 43000)
            self.assertEqual(config['short_name'], 'FF')
            self.assertEqual(config['paths']['native_solution'], 'src/platform/win/FF.sln')
            self.assertEqual(config['paths']['native_executable'], 'bin/FF.exe')
            self.assertIn('// XPORT REVISION:', (root/'src/game_main.c').read_text())
            self.assertTrue((root/'src/platform/win/FF.sln').is_file())
            self.assertIn('Native short name: `FF`', (root/'AGENTS.md').read_text(encoding='utf-8'))
            project = (root/'src/platform/win/FF.vcxproj').read_text(encoding='utf-8')
            solution = (root/'src/platform/win/FF.sln').read_text(encoding='utf-8')
            self.assertIn('Debug|x86 = Debug|x86', solution)
            self.assertIn('Release|x86 = Release|x86', solution)
            self.assertIn('Debug|Win32', project)
            self.assertIn('Release|Win32', project)
            self.assertEqual(project.count('<SubSystem>Windows</SubSystem>'), 2)
            self.assertNotIn('<EntryPointSymbol>', project)
            self.assertNotIn('<SubSystem>Console</SubSystem>', project)
            self.assertIn('<CompileAs>CompileAsC</CompileAs>', project)
            self.assertIn('<TargetName>FF</TargetName>', project)
            self.assertIn(r'<OutDir>$(ProjectDir)..\..\..\bin\</OutDir>', project)
            self.assertIn('psx_spu.c', project)
            self.assertIn('psx_gpu.c', project)
            self.assertIn('platform\\win\\main.c', project)
            self.assertIn('\\xport.h', project)
            self.assertNotIn('xport_game.h', project)
            self.assertNotIn('xport_platform.h', project)
            self.assertIn('WND_TITLE=&quot;Fighting Force (xport)&quot;', project)
            self.assertIn('WND_WIDTH=960', project)
            self.assertIn('WND_HEIGHT=768', project)
            self.assertIn('FIELD_RATE=50', project)
            self.assertIn('winmm.lib', project)
            main = (root/'src/game_main.c').read_text(encoding='utf-8')
            self.assertIn('int xport_main(int argc, char **argv)', main)
            self.assertNotIn('audio_runtime_render', main)
            self.assertNotIn('spu_render', main)
            self.assertNotIn('xport_address', main)
            self.assertNotIn('xport_audio_output_environment', main)
            self.assertEqual({path.name for path in (root/'src/platform/win').iterdir()}, {'FF.sln', 'FF.vcxproj'})
            self.assertIn('#include "xport.h"', main)
            self.assertEqual(main.count('#include "xport.h"'), 1)
            self.assertFalse((root/'src/xport.h').exists())
            agents = (root/'AGENTS.md').read_text(encoding='utf-8')
            self.assertIn('`bin/FF.exe` is directly under `bin`', agents)
            self.assertIn('`bin/DATA` contains data extracted from the first CD data track', agents)
            self.assertIn('`bin/MUSIC` contains decimal-name IMA ADPCM WAV tracks generated by `convert_music`', agents)
            self.assertEqual(json.loads((root/'status/translation-ledger.json').read_text())['entries'], [])

    def test_source_index_accepts_generic_and_legacy_function_markers(self):
        text = '''int first(void)\n{\n    FUNCTION_MARKER(0x80010000u, "GAME.EXE");\n    return 1;\n}\n\nint second(void)\n{\n    FF_FUNCTION_MARKER(0x80010004u, "GAME.EXE");\n    return 2;\n}\n'''
        parsed = source_index.functions(text, 'src/game.c')
        self.assertEqual(parsed[0]['markers'], [(0x80010000, 'GAME.EXE')])
        self.assertEqual(parsed[1]['markers'], [(0x80010004, 'GAME.EXE')])

    def test_initializer_rejects_derived_or_unsafe_short_names(self):
        for value in ('', 'Fighting Force', '1FF', 'name-with-dash', 'A'*17, 'CON'):
            with self.subTest(value=value), self.assertRaises(ValueError):
                project_init.validate_names('Fighting Force', value)

    def test_initializer_rejects_unsafe_window_titles(self):
        for value in ('Bad "Title', 'Bad;Title', 'Bad\nTitle'):
            with self.subTest(value=value), self.assertRaises(ValueError):
                project_init.validate_names(value, 'SAFE')

    def test_accept_publishes_only_complete_canonical_export(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)/'Example-xport'
            project_init.initialize(root, 'Example Game', 'EX', 43100)
            config = root/'tools/ida/GAME.EXE.json'
            config.write_text('{}\n', encoding='utf-8')
            image = root/'status/ida/runs/export-v1/GAME.EXE'
            (image/'functions').mkdir(parents=True)
            (image/'pseudocode').mkdir()
            word = bytes.fromhex('00000000')
            function = {'address': 0x80010000, 'sha256': hashlib.sha256(word).hexdigest(),
                        'raw_instructions': [{'address': 0x80010000, 'bytes': word.hex()}],
                        'pseudocode': 'pseudocode/80010000.c'}
            (image/'functions.json').write_text(json.dumps([function]), encoding='utf-8')
            (image/'export-report.json').write_text(json.dumps({'image': 'GAME.EXE', 'source_bytes_verified': True,
                                                                 'independent_decoder': 'capstone test',
                                                                 'raw_instruction_words': 1}), encoding='utf-8')
            (image/'functions/80010000.lst').write_text('listing\n', encoding='utf-8')
            (image/'functions/80010000.mips.txt').write_text('mips\n', encoding='utf-8')
            (image/'pseudocode/80010000.c').write_text('void f(void) {}\n', encoding='utf-8')
            (image/'GAME.EXE.lst').write_text('listing\n', encoding='utf-8')
            (image/'GAME.EXE.c').write_text('void f(void) {}\n', encoding='utf-8')
            previous = os.environ.get('XPORT_PROJECT')
            os.environ['XPORT_PROJECT'] = str(root)
            try:
                result = ida_accept.accept('export-v1', ['GAME.EXE'])
                self.assertEqual(result['accepted'], ['GAME.EXE'])
                self.assertTrue((root/'orig/images/GAME.EXE/functions/80010000.mips.txt').is_file())
                receipt = json.loads((root/result['receipt']).read_text())
                self.assertEqual(receipt['images'][0]['functions'], 1)
                with self.assertRaises(ValueError):
                    ida_accept.accept('export-v1', ['GAME.EXE'])
            finally:
                if previous is None:
                    os.environ.pop('XPORT_PROJECT', None)
                else:
                    os.environ['XPORT_PROJECT'] = previous


if __name__ == '__main__':
    unittest.main()
